name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build Angular
      run: ng build --prod

    - name: Build NestJS
      run: npm run build

    - name: Deploy
      run: |
        scp -r dist/* ${{ secrets.SSH_USER }}@${ { secrets.SSH_HOST }}:${ { secrets.SSH_PATH }}
        scp -r dist/* ${{ secrets.SSH_USER }}@${ { secrets.SSH_HOST }}:${ { secrets.SSH_PATH_ANGULAR }}
